// Generated by CoffeeScript 1.6.2
(function() {
  define('openEpi', ['modules', 'angular', 'angular-twitter-bootstrap', 'angular-grid'], function(modules) {
    var errorHandler, getModule, openEpi;

    openEpi = angular.module('openEpi', ['ui.bootstrap', 'ngGrid']);
    errorHandler = function(message) {
      console.log('Error: ');
      return console.log(message);
    };
    getModule = function(moduleName) {
      var module;

      module = modules.getModule(moduleName);
      if (module == null) {
        errorHandler("Could not find module named " + moduleName);
        return null;
      }
      return module;
    };
    openEpi.config([
      '$routeProvider', function($routeProvider) {
        $routeProvider.when('/', {
          templateUrl: 'partials/modules.html',
          controller: 'ModulesController'
        });
        $routeProvider.when('/module/:moduleName', {
          templateUrl: 'partials/module.html',
          controller: 'ModuleController'
        });
        $routeProvider.when('/about', {
          templateUrl: 'partials/about.html',
          controller: 'AboutController'
        });
        return $routeProvider.otherwise({
          redirectTo: '/'
        });
      }
    ]);
    openEpi.controller('ModulesController', [
      '$rootScope', '$scope', '$location', function($rootScope, $scope, $location) {
        $scope.modules = modules.allModules();
        $scope.moduleLoad = function(moduleName) {
          return $location.path('/module/' + moduleName);
        };
        $scope.moduleFilter = function(module, filterTerm) {
          var tag, _i, _len, _ref;

          if (filterTerm == null) {
            return true;
          }
          if (module.title.toLowerCase().indexOf(filterTerm.toLowerCase()) > -1) {
            return true;
          }
          _ref = module.tags;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            tag = _ref[_i];
            if (tag.toLowerCase().indexOf(filterTerm.toLowerCase()) > -1) {
              return true;
            }
          }
          return false;
        };
        $scope.detailsTitle = function(detailsShown) {
          if (!detailsShown) {
            return "More Info";
          }
          return "Less Info";
        };
        $scope.myData = [
          {
            name: "Moroni",
            age: 50
          }, {
            name: "Tiancum",
            age: 43
          }, {
            name: "Jacob",
            age: 27
          }, {
            name: "Nephi",
            age: 29
          }, {
            name: "Enos",
            age: 34
          }
        ];
        return $scope.gridOptions = {
          data: 'myData',
          enableCellSelection: true,
          enableRowSelection: false,
          enableCellEdit: true,
          columnDefs: [
            {
              field: 'name',
              displayName: 'Name',
              enableCellEdit: true
            }, {
              field: 'age',
              displayName: 'Age',
              enableCellEdit: false
            }
          ]
        };
      }
    ]);
    openEpi.controller('ModuleController', [
      '$rootScope', '$scope', '$routeParams', '$location', function($rootScope, $scope, $routeParams, $location) {
        var module;

        module = getModule($routeParams.moduleName);
        module.resetInputModel();
        $scope.module = module;
        $scope.hasResult = false;
        $scope.result = {
          resultPaneActive: false
        };
        $scope.getDefaultValue = function(field) {
          if (field.defaultValue != null) {
            return field.defaultValue;
          }
          return '';
        };
        $scope.calculate = function() {
          return module.calculate(module.model, errorHandler, function(result) {
            return module.renderData(result, function(data) {
              $scope.hasResult = true;
              $scope.result = data;
              return $scope.result.resultPaneActive = true;
            });
          });
        };
        return $scope.clear = function() {
          return module.resetInputModel();
        };
      }
    ]);
    openEpi.controller('AboutController', function() {});
    angular.bootstrap(document, ['openEpi']);
    return openEpi;
  });

}).call(this);
