// Generated by CoffeeScript 1.6.2
(function() {
  var createServer, express, fs;

  express = require('express');

  fs = require('fs');

  createServer = function() {
    var app;

    app = express();
    app.configure(function() {
      var port;

      app.use('/app', express["static"]('../../'));
      app.use(express.bodyParser());
      app.use(app.router);
      port = process.env.PORT || 8081;
      return app.listen(port);
    });
    app.get('/modules', function(req, res) {
      var dir, file, files, stat, _i, _len;

      dir = __dirname + '/../../js/modules/';
      files = fs.readdirSync(dir);
      for (_i = 0, _len = files.length; _i < _len; _i++) {
        file = files[_i];
        stat = fs.statSync(dir + file);
        if (stat.isDirectory()) {
          console.log(file);
        }
      }
      return res.send('some data');
    });
    return app;
  };

  module.exports = createServer;

}).call(this);
